M48
; DRILL file KiCad 10.0.6 date 2026-09-03T18:11:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-03T18:11:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T2
X175.32Y-126.89
T3
X154.686Y-84.073
X154.686Y-112.523
T1
X175.32Y-134.18G85X175.32Y-134.6
G05
M30
