// The CDI: an XML description of the configuration space, read by JMRI's
// "Configure Nodes" tool (and any other LCC configuration tool) to draw a form.
//
// Every field here must land on the offset Config.h gives it. Sizes add up in
// document order: an <int> is its size in bytes, an <eventid> 8, a <string>
// its size, and a replicated group its contents times the replication. After
// changing either file, run:
//
//   python3 software/tools/check_cdi.py

#include "Config.h"

const char CDI_XML[] =
"<?xml version='1.0'?>"
"<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'"
" xsi:noNamespaceSchemaLocation='http://openlcb.org/schema/cdi/1/1/cdi.xsd'>"

"<identification>"
"<manufacturer>Uncommon Models</manufacturer>"
"<model>FemtoLCC</model>"
"<hardwareVersion>v1</hardwareVersion>"
"<softwareVersion>" FEMTOLCC_VERSION "</softwareVersion>"
"</identification>"
"<acdi/>"

AOLCB_CDI_USER_INFO

"<segment space='253' origin='128'>"
"<name>Settings</name>"
"<description>Changes to the outputs, I/O pins and expansion boards take effect a"
" moment after they are written. WiFi changes take effect after the node is"
" rebooted.</description>"

// Bytes 128-131 hold the layout magic, which a tool has no business editing.
"<group offset='4'/>"

// --- output channels A-D ----------------------------------------------------
"<group replication='4'>"
"<name>Outputs</name>"
"<description>The four block driver outputs. Output 1 is channel A (terminal"
" J5), through output 4, channel D (J8). Each drives either a track block or a"
" turnout motor.</description>"
"<repname>Output </repname>"

"<int size='1'><name>Use</name>"
"<description>What this output is wired to. An unused output is held off and"
" sends no events.</description>"
"<default>1</default>"
"<map>"
"<relation><property>0</property><value>Unused</value></relation>"
"<relation><property>1</property><value>Track block</value></relation>"
"<relation><property>2</property><value>Turnout motor</value></relation>"
"</map></int>"

"<eventid><name>Fault</name>"
"<description>Produced when the driver reports overcurrent, overtemperature or"
" undervoltage. The output is switched off until it is commanded again.</description>"
"</eventid>"

"<group><name>Track block</name>"
"<description>Used when the output drives a track block. Detection while off,"
" the last section of this form, applies to a track block too: it is a section of"
" its own only because of where its settings sit in the node's memory.</description>"
"<int size='1'><name>At power-on</name>"
"<description>What the block does when the node starts.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Off</value></relation>"
"<relation><property>1</property><value>DC, full power</value></relation>"
"<relation><property>2</property><value>DCC pass-through</value></relation>"
"</map></int>"
"<int size='1'><name>DCC polarity</name>"
"<description>Reversed swaps the rails while passing DCC through, for a reversing"
" section.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Normal</value></relation>"
"<relation><property>1</property><value>Reversed</value></relation>"
"</map></int>"
"<int size='2'><name>Occupied at (mA)</name>"
"<description>The block is reported occupied once it draws at least this much"
" current. A 4.7k resistive wheelset draws about 3 mA.</description>"
"<min>1</min><max>3000</max><default>5</default></int>"
"<int size='2'><name>Clear below (mA)</name>"
"<description>The block is reported clear once the current falls below this."
" Keep it under the occupied level so a load on the threshold does not"
" chatter.</description>"
"<min>0</min><max>3000</max><default>3</default></int>"
"<eventid><name>Power on (DC)</name>"
"<description>Consumed: drive the block with full-power DC.</description></eventid>"
"<eventid><name>Power off</name>"
"<description>Consumed: switch the block off.</description></eventid>"
"<eventid><name>DCC on</name>"
"<description>Consumed: pass the DCC track signal through to the block.</description></eventid>"
"<eventid><name>Occupied</name>"
"<description>Produced when something starts drawing current in the block.</description></eventid>"
"<eventid><name>Clear</name>"
"<description>Produced when the block empties.</description></eventid>"
"</group>"

"<group><name>Turnout motor</name>"
"<description>Used when the output drives a turnout motor.</description>"
"<int size='1'><name>Motor type</name>"
"<description>Stall motors (Tortoise, Cobalt and similar) are driven continuously,"
" one polarity per position. Pulse motors (two-wire latching motors such as Kato"
" or Peco with a capacitor-free drive) get one polarity for the pulse length,"
" then the output switches off.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Stall motor</value></relation>"
"<relation><property>1</property><value>Pulse</value></relation>"
"</map></int>"
"<int size='2'><name>Pulse length (ms)</name>"
"<description>How long a pulse motor is driven. Ignored for stall motors.</description>"
"<min>10</min><max>5000</max><default>200</default></int>"
"<int size='1'><name>Drive strength</name>"
"<description>PWM duty, 0 to 255. 255 applies the full supply voltage; lower it to"
" run a stall motor slower and cooler.</description>"
"<min>0</min><max>255</max><default>255</default></int>"
"<int size='1'><name>Direction</name>"
"<description>Reverse this if the turnout throws when it should close.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Normal</value></relation>"
"<relation><property>1</property><value>Reversed</value></relation>"
"</map></int>"
"<int size='1'><name>At power-on</name>"
"<description>Where the turnout is set when the node starts. Leave alone does not"
" drive it, and its position is unknown until it is next commanded.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Closed</value></relation>"
"<relation><property>1</property><value>Thrown</value></relation>"
"<relation><property>2</property><value>Leave alone</value></relation>"
"</map></int>"
"<eventid><name>Throw</name>"
"<description>Consumed: throw the turnout.</description></eventid>"
"<eventid><name>Close</name>"
"<description>Consumed: close the turnout.</description></eventid>"
"<eventid><name>Thrown</name>"
"<description>Produced once the turnout has been commanded thrown.</description></eventid>"
"<eventid><name>Closed</name>"
"<description>Produced once the turnout has been commanded closed.</description></eventid>"
"</group>"
"</group>"

// --- expander port A --------------------------------------------------------
"<group replication='8'>"
"<name>I/O pins</name>"
"<description>The eight general-purpose lines on the MCP23018 expander. Pin 1 is"
" P0, through pin 8, P7. Outputs are open drain: they can only pull a line to"
" ground, so wire an LED or relay from the supply through a resistor into the"
" pin.</description>"
"<repname>Pin </repname>"
"<int size='1'><name>Mode</name>"
"<description>Input with pull-up suits a switch or contact to ground. Unused pins"
" are inputs with the pull-up on.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Unused</value></relation>"
"<relation><property>1</property><value>Input</value></relation>"
"<relation><property>2</property><value>Input with pull-up</value></relation>"
"<relation><property>3</property><value>Output</value></relation>"
"</map></int>"
"<int size='1'><name>Polarity</name>"
"<description>Normally an input is active when pulled to ground, and an output"
" pulls to ground when on. Inverted swaps both.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Normal</value></relation>"
"<relation><property>1</property><value>Inverted</value></relation>"
"</map></int>"
"<int size='2'><name>Debounce (ms)</name>"
"<description>How long an input must hold a new level before it counts.</description>"
"<min>0</min><max>5000</max><default>20</default></int>"
"<eventid><name>Input active</name>"
"<description>Produced when the input becomes active.</description></eventid>"
"<eventid><name>Input inactive</name>"
"<description>Produced when the input becomes inactive.</description></eventid>"
"<eventid><name>Output on</name>"
"<description>Consumed: turn the output on.</description></eventid>"
"<eventid><name>Output off</name>"
"<description>Consumed: turn the output off.</description></eventid>"
"</group>"

// --- WiFi -------------------------------------------------------------------
"<group><name>WiFi</name>"
"<description>LCC over WiFi, as GridConnect over TCP. Changes here take effect"
" after the node is rebooted.</description>"
"<int size='1'><name>WiFi</name>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Disabled</value></relation>"
"<relation><property>1</property><value>Enabled</value></relation>"
"</map></int>"
"<string size='33'><name>Network name (SSID)</name></string>"
"<string size='64'><name>Password</name>"
"<description>Reads back blank so it cannot be copied off the node. Leave it blank"
" to keep the stored password.</description></string>"
"<string size='32'><name>Hostname</name>"
"<description>The node's name on the network. It answers as hostname.local.</description>"
"</string>"
"<int size='1'><name>Hub mode</name>"
"<description>Act as a hub: JMRI and other nodes connect to this node. Connect to a"
" hub: this node connects out to the address below.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Act as a hub</value></relation>"
"<relation><property>1</property><value>Connect to a hub</value></relation>"
"</map></int>"
"<string size='64'><name>Hub address</name>"
"<description>Host name or IP address of the hub, when connecting to one.</description>"
"</string>"
"<int size='2'><name>TCP port</name>"
"<description>The port listened on as a hub, or connected to. 12021 is the LCC"
" standard.</description>"
"<min>1</min><max>65535</max><default>12021</default></int>"
"</group>"

// --- USB --------------------------------------------------------------------
"<group><name>USB</name>"
"<description>The USB port carries the serial console, and can carry LCC as"
" GridConnect too, so the board works as a USB adapter for JMRI (an LCC"
" connection, CAN via GridConnect, on the board's serial port). Traffic is"
" bridged to the CAN bus and WiFi.</description>"
"<int size='1'><name>GridConnect output</name>"
"<description>Automatic starts sending LCC traffic to USB when the computer sends"
" its first GridConnect frame, which JMRI does as it connects. Always on sends it"
" from power-on. Off keeps the port a plain console. While traffic is being"
" sent, the console stops printing status messages of its own.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Automatic</value></relation>"
"<relation><property>1</property><value>Always on</value></relation>"
"<relation><property>2</property><value>Off</value></relation>"
"</map></int>"
"</group>"

// Bytes 990-993 hold the expansion magic.
"<group offset='4'/>"

// --- I/O expansion boards ---------------------------------------------------
"<group replication='4'>"
"<name>I/O expansion boards</name>"
"<description>Up to four I/O expander boards on the Qwiic connector J3, each adding"
" 8 or 16 lines that work like the I/O pins. Set each board's address with its"
" jumpers or switches, and choose the same address here. No two boards may share an"
" address. A board plugged in later is found within a few seconds.</description>"
"<repname>Board </repname>"
"<int size='1'><name>Board type</name>"
"<description>The chip on the board. MCP23017: 16 lines, with pull-ups. PCF8574 or"
" PCF8574A: 8 lines. Its outputs can only pull low, and every input has a weak"
" pull-up. It is a 100 kHz chip, so the whole bus runs at 100 kHz while one is set"
" up. TCA9534 or PCA9554, as on SparkFun's Qwiic GPIO: 8 lines, no"
" pull-ups.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>None</value></relation>"
"<relation><property>1</property><value>MCP23017 (16 lines)</value></relation>"
"<relation><property>2</property><value>PCF8574 or PCF8574A (8 lines)</value></relation>"
"<relation><property>3</property><value>TCA9534 or PCA9554 (8 lines)</value></relation>"
"</map></int>"
"<int size='1'><name>I2C address</name>"
"<description>MCP23017: 0x21 to 0x27. PCF8574, TCA9534 and PCA9554: 0x21 to 0x27, or"
" 0x38 to 0x3F for the PCF8574A, TCA9534A and PCA9554A. 0x20 belongs to the expander on"
" this board, and many expansion boards come set to it: move them with their address"
" jumpers first.</description>"
"<default>33</default>"
"<map>"
"<relation><property>33</property><value>0x21</value></relation>"
"<relation><property>34</property><value>0x22</value></relation>"
"<relation><property>35</property><value>0x23</value></relation>"
"<relation><property>36</property><value>0x24</value></relation>"
"<relation><property>37</property><value>0x25</value></relation>"
"<relation><property>38</property><value>0x26</value></relation>"
"<relation><property>39</property><value>0x27</value></relation>"
"<relation><property>56</property><value>0x38</value></relation>"
"<relation><property>57</property><value>0x39</value></relation>"
"<relation><property>58</property><value>0x3A</value></relation>"
"<relation><property>59</property><value>0x3B</value></relation>"
"<relation><property>60</property><value>0x3C</value></relation>"
"<relation><property>61</property><value>0x3D</value></relation>"
"<relation><property>62</property><value>0x3E</value></relation>"
"<relation><property>63</property><value>0x3F</value></relation>"
"</map></int>"

"<group replication='16'>"
"<name>Lines</name>"
"<description>Line 1 is the chip's first pin. On an MCP23017 lines 1 to 8 are GPA0"
" to GPA7 (A0-A7) and lines 9 to 16 are GPB0 to GPB7 (B0-B7); current MCP23017s allow"
" only outputs on GPA7 and GPB7, lines 8 and 16. On the 8-line chips, lines 1 to 8"
" are P0 to P7 and lines 9 to 16 are not used.</description>"
"<repname>Line </repname>"
"<int size='1'><name>Mode</name>"
"<description>Input with pull-up suits a switch or contact to ground. The TCA9534"
" and PCA9554 have no pull-ups, so fit a resistor to 3.3 V. Unused lines are"
" inputs.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Unused</value></relation>"
"<relation><property>1</property><value>Input</value></relation>"
"<relation><property>2</property><value>Input with pull-up</value></relation>"
"<relation><property>3</property><value>Output</value></relation>"
"</map></int>"
"<int size='1'><name>Polarity</name>"
"<description>As for the I/O pins: an input is active when pulled to ground, and an"
" output pulls to ground when on. Inverted swaps both, so an output drives high"
" when on (only weakly, on a PCF8574).</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Normal</value></relation>"
"<relation><property>1</property><value>Inverted</value></relation>"
"</map></int>"
"<int size='2'><name>Debounce (ms)</name>"
"<description>How long an input must hold a new level before it counts.</description>"
"<min>0</min><max>5000</max><default>20</default></int>"
"<eventid><name>Input active</name>"
"<description>Produced when the input becomes active.</description></eventid>"
"<eventid><name>Input inactive</name>"
"<description>Produced when the input becomes inactive.</description></eventid>"
"<eventid><name>Output on</name>"
"<description>Consumed: turn the output on.</description></eventid>"
"<eventid><name>Output off</name>"
"<description>Consumed: turn the output off.</description></eventid>"
"</group>"
"</group>"

// --- servo and light boards -------------------------------------------------
"<group replication='2'>"
"<name>Servo and light boards</name>"
"<description>Up to two PCA9685 16-channel PWM boards on the Qwiic connector J3, such"
" as Adafruit's 16-channel servo driver or SparkFun's Qwiic servo driver, driving"
" servo turnouts or lights. Power the servos from a separate 5-6 V supply into the"
" board's power terminal, never from the Qwiic 3.3 V pin.</description>"
"<repname>Board </repname>"
"<int size='1'><name>Board type</name>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>None</value></relation>"
"<relation><property>1</property><value>PCA9685 (16 channels)</value></relation>"
"</map></int>"
"<int size='1'><name>I2C address</name>"
"<description>0x40 until address jumpers are bridged: A0 adds 1, A1 2, A2 4, A3 8, A4"
" 16 and A5 32. Avoid 0x70, which every PCA9685 also answers until it is set"
" up.</description>"
"<default>64</default>"
"<map>"
"<relation><property>64</property><value>0x40</value></relation>"
"<relation><property>65</property><value>0x41</value></relation>"
"<relation><property>66</property><value>0x42</value></relation>"
"<relation><property>67</property><value>0x43</value></relation>"
"<relation><property>68</property><value>0x44</value></relation>"
"<relation><property>69</property><value>0x45</value></relation>"
"<relation><property>70</property><value>0x46</value></relation>"
"<relation><property>71</property><value>0x47</value></relation>"
"<relation><property>72</property><value>0x48</value></relation>"
"<relation><property>73</property><value>0x49</value></relation>"
"<relation><property>74</property><value>0x4A</value></relation>"
"<relation><property>75</property><value>0x4B</value></relation>"
"<relation><property>76</property><value>0x4C</value></relation>"
"<relation><property>77</property><value>0x4D</value></relation>"
"<relation><property>78</property><value>0x4E</value></relation>"
"<relation><property>79</property><value>0x4F</value></relation>"
"<relation><property>80</property><value>0x50</value></relation>"
"<relation><property>81</property><value>0x51</value></relation>"
"<relation><property>82</property><value>0x52</value></relation>"
"<relation><property>83</property><value>0x53</value></relation>"
"<relation><property>84</property><value>0x54</value></relation>"
"<relation><property>85</property><value>0x55</value></relation>"
"<relation><property>86</property><value>0x56</value></relation>"
"<relation><property>87</property><value>0x57</value></relation>"
"<relation><property>88</property><value>0x58</value></relation>"
"<relation><property>89</property><value>0x59</value></relation>"
"<relation><property>90</property><value>0x5A</value></relation>"
"<relation><property>91</property><value>0x5B</value></relation>"
"<relation><property>92</property><value>0x5C</value></relation>"
"<relation><property>93</property><value>0x5D</value></relation>"
"<relation><property>94</property><value>0x5E</value></relation>"
"<relation><property>95</property><value>0x5F</value></relation>"
"<relation><property>96</property><value>0x60</value></relation>"
"<relation><property>97</property><value>0x61</value></relation>"
"<relation><property>98</property><value>0x62</value></relation>"
"<relation><property>99</property><value>0x63</value></relation>"
"<relation><property>100</property><value>0x64</value></relation>"
"<relation><property>101</property><value>0x65</value></relation>"
"<relation><property>102</property><value>0x66</value></relation>"
"<relation><property>103</property><value>0x67</value></relation>"
"<relation><property>104</property><value>0x68</value></relation>"
"<relation><property>105</property><value>0x69</value></relation>"
"<relation><property>106</property><value>0x6A</value></relation>"
"<relation><property>107</property><value>0x6B</value></relation>"
"<relation><property>108</property><value>0x6C</value></relation>"
"<relation><property>109</property><value>0x6D</value></relation>"
"<relation><property>110</property><value>0x6E</value></relation>"
"<relation><property>111</property><value>0x6F</value></relation>"
"<relation><property>112</property><value>0x70</value></relation>"
"<relation><property>113</property><value>0x71</value></relation>"
"<relation><property>114</property><value>0x72</value></relation>"
"<relation><property>115</property><value>0x73</value></relation>"
"<relation><property>116</property><value>0x74</value></relation>"
"<relation><property>117</property><value>0x75</value></relation>"
"<relation><property>118</property><value>0x76</value></relation>"
"<relation><property>119</property><value>0x77</value></relation>"
"<relation><property>120</property><value>0x78</value></relation>"
"<relation><property>121</property><value>0x79</value></relation>"
"<relation><property>122</property><value>0x7A</value></relation>"
"<relation><property>123</property><value>0x7B</value></relation>"
"<relation><property>124</property><value>0x7C</value></relation>"
"<relation><property>125</property><value>0x7D</value></relation>"
"<relation><property>126</property><value>0x7E</value></relation>"
"<relation><property>127</property><value>0x7F</value></relation>"
"</map></int>"
"<int size='1'><name>Servos at rest</name>"
"<description>Stop pulses: once a servo reaches its position its pulses stop, so it"
" cannot buzz or hunt, and the turnout's throwbar holds it there. Hold position: keep"
" driving it, for a servo that has to push against a spring.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Stop pulses</value></relation>"
"<relation><property>1</property><value>Hold position</value></relation>"
"</map></int>"

"<group replication='16'>"
"<name>Channels</name>"
"<description>Channel 1 is the output marked 0 on the board, through channel 16,"
" marked 15.</description>"
"<repname>Channel </repname>"
"<int size='1'><name>Use</name>"
"<description>A servo turnout moves slowly between its closed and thrown positions."
" A light fades between off and its brightness; an inverted light is lit when the"
" output is low, for an LED wired from the supply into the pin. The rest of each"
" choice is where the channel goes when the node starts. Left alone sends no pulse"
" until the first command, and that first move is at the servo's own"
" speed.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>Unused</value></relation>"
"<relation><property>1</property><value>Servo turnout, closed at power-on</value></relation>"
"<relation><property>2</property><value>Servo turnout, thrown at power-on</value></relation>"
"<relation><property>3</property><value>Servo turnout, left alone at power-on</value></relation>"
"<relation><property>4</property><value>Light, off at power-on</value></relation>"
"<relation><property>5</property><value>Light, on at power-on</value></relation>"
"<relation><property>6</property><value>Inverted light, off at power-on</value></relation>"
"<relation><property>7</property><value>Inverted light, on at power-on</value></relation>"
"</map></int>"
"<eventid><name>Throw / light on</name>"
"<description>Consumed: throw the servo turnout, or switch the light on.</description></eventid>"
"<eventid><name>Close / light off</name>"
"<description>Consumed: close the servo turnout, or switch the light off.</description></eventid>"
"<int size='2'><name>Travel or fade time (ms)</name>"
"<description>How long a servo takes from closed to thrown, or a light from off to"
" full brightness. 0 moves at once.</description>"
"<min>0</min><max>60000</max><default>1000</default></int>"
"<group><name>Servo turnout</name>"
"<description>Used when the channel drives a servo turnout. Find the positions with"
" the console command servo, for example servo 1 1 1500 for board 1, channel 1. To"
" reverse a servo, swap the two positions.</description>"
"<int size='2'><name>Closed position (&#181;s)</name>"
"<description>The pulse width for closed. 1500 is the middle of a servo's travel,"
" and most servos turn about 90 degrees between 1000 and 2000.</description>"
"<min>500</min><max>2500</max><default>1300</default></int>"
"<int size='2'><name>Thrown position (&#181;s)</name>"
"<description>The pulse width for thrown.</description>"
"<min>500</min><max>2500</max><default>1700</default></int>"
"<eventid><name>Thrown</name>"
"<description>Produced when the servo reaches the thrown position.</description></eventid>"
"<eventid><name>Closed</name>"
"<description>Produced when the servo reaches the closed position.</description></eventid>"
"</group>"
"<group><name>Light</name>"
"<description>Used when the channel drives a light.</description>"
"<int size='1'><name>Brightness</name>"
"<description>How bright the light is when on, 0 to 255. The scale follows the eye,"
" so 128 looks about half as bright as 255.</description>"
"<min>0</min><max>255</max><default>255</default></int>"
"</group>"
"</group>"
"</group>"

// --- detection while off ----------------------------------------------------
// Four bytes an output, in what was left at the end of the space. These belong
// with Track block above, but that group's replicas are fixed at CFG_CH_SIZE
// bytes from 132 and nothing may move, so they are a group of their own here.
"<group replication='4'>"
"<name>Detection while off</name>"
"<description>Occupancy detection for a block that has no power on it. The board"
" pulses the block briefly, measures the current during the pulse and switches it"
" off again, so a block that is switched off still reports occupied or clear. This"
" is what lets a dispatcher see where a train is standing in a block it is not"
" powering. The pulse is a couple of milliseconds every few hundred - far too short"
" to move a locomotive, and about a hundredth of the power a lamp needs to light."
" These settings belong with Track block above, and are here only because their"
" bytes are at the end of the configuration space.</description>"
"<repname>Output </repname>"
"<int size='1'><name>Detect while off</name>"
"<description>Pulse the block while it is switched off, so it can still be"
" detected. On by default. Turn it off if lit stock in the block flickers. It is"
" ignored unless the output is a track block, and no pulse is ever sent while the"
" block is powered, is passing DCC through, or its driver has faulted.</description>"
"<default>0</default>"
"<map>"
"<relation><property>0</property><value>On</value></relation>"
"<relation><property>1</property><value>Off</value></relation>"
"</map></int>"
"<int size='1'><name>Pulse length (100 &#181;s)</name>"
"<description>How long each pulse lasts, in hundreds of microseconds: 20 is 2 ms,"
" the default. A longer pulse reads more steadily, a shorter one is less visible in"
" lit stock. 10 to 50; 0 uses the default.</description>"
"<min>0</min><max>50</max><default>20</default></int>"
"<int size='2'><name>Pulse interval (ms)</name>"
"<description>How often each block is pulsed. 300 ms is the default, and the four"
" outputs are spread across the interval so only one is ever pulsing. 100 to 10000;"
" 0 uses the default.</description>"
"<min>0</min><max>10000</max><default>300</default></int>"
"</group>"

"</segment>"
"</cdi>";
